name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Execute unit tests
      - name: Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.19.1
        with: 
            api-level: 29
            script: ./gradlew jacocoUnitTestReport
      
      - name: upload reports unit test reports
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: |
            **/build/reports/coverage/jacocoUnitTestReport/jacocoUnitTestReport.xml
            **/build/reports/coverage/androidTest/debug/report.xml


#      - name: Download Test Reports Folder
#        uses: actions/download-artifact@v2
#        with:
#          name: report
#          path: app/build/reports/coverage/debug
#
#      - name: Upload Test Report
#        run:  bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/debug/report.xml"
